WWW

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,18 +1,33 @@
 #!/usr/bin/env bash
 # Function to display subdomain information
 
-domain_information () {
-    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+domain=$1
+subdomain=$2
+
+# Function to print domain information
+print_domain_info() {
+    local record_type=$(echo "$result" | awk '{print $4}')
+    local ip_addr=$(echo "$result" | awk '{print $5}')
+    echo "The subdomain $subdomain is a $record_type record and points to $ip_addr"
 }
 
-if [ "$#" == 1 ]
-then
-  domain_information "$1" "www"
-  domain_information "$1" "lb-01"
-  domain_information "$1" "web-01"
-  domain_information "$1" "web-02"
-elif [ "$#" == 2 ]
-then
-  domain_information "$1" "$2"
-fi
+# Function to get domain information
+get_domain_info() {
+    if [[ -z $domain ]]; then
+        echo "Domain name missing."
+        exit 1
+    fi
+
+    if [[ -z $subdomain ]]; then
+        known_sub_domains=("www" "lb-01" "web-01" "web-02")
+        for sub in "${known_sub_domains[@]}"; do
+            result=$(dig "$sub.$domain" | awk '/^'${sub}'\.'${domain}'\./ { print $0 }' | tail -1)
+            print_domain_info
+        done
+    else
+        result=$(dig "$subdomain.$domain" | awk '/^'${subdomain}'\.'${domain}'\./ { print $0 }' | tail -1)
+        print_domain_info
+    fi
+}
+
+get_domain_info
