Install Nginx server

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,36 +1,45 @@
 #!/usr/bin/env bash
 # This script installs, configures, and starts the server
 
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: You need to be root to run this script" 1>&2
+  exit 1
+fi
+
+# Update the package list and install Nginx
 apt-get update
 apt-get install -y nginx
 
-# Create custom 404 page with the string "Ceci n'est pas une page"
-echo '<!DOCTYPE html>
-<html>
-<head>
-    <title>404 Not Found</title>
-</head>
-<body>
-    <h1>404 Not Found</h1>
-    <p>Ceci n'\''est pas une page</p>
-</body>
-</html>' > /usr/share/nginx/html/404.html
+# Create the default "Hello world" page
+echo "Hello World!" > /var/www/html/index.html
 
-# Configure nginx to use the custom 404 page
-echo 'server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
+# configure error 404 page
+echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
 
-    root /var/www/html;
-    index index.html index.htm index.nginx-debian.html;
+# confifure the server for redirection and 404 page
+echo -e "\tserver_name _;
+\tlocation /redirect_me {
+\t\treturn 301 https://lzcorp-landing-page.vercel.app/;
+\t}
 
-    server_name _;
+\terror_page 404 /404.html;
+\tlocation = /404.html {
+\t\troot /usr/share/nginx/html;
+\t\tinternal;
+\t}
+" > /tmp/new_config
 
-    error_page 404 /404.html;
-    location = /404.html {
-        internal;
-    }
-}' > /etc/nginx/sites-available/default
+sed -i '/server_name _;/{
+    r /tmp/new_config
+}' /etc/nginx/sites-available/default
 
-# Restart nginx
-service nginx restart
+# Remove the temporary configuration file
+rm /tmp/new_config
+
+# Start the Nginx service
+service nginx start
+
+if [[ ! $? ]]; then
+  echo "ERROR: Failed to start Nginx" 1>&2
+  exit 1
+fi
